#!/usr/bin/env zsh

## env setup
fpath=(/usr/lib/zsh_libmisc/libmisc.zwc $fpath)
autoload libmiscinit
libmiscinit

! isfile ./permutator && \
  cc ./permutator.c -o permutator
! isfile ./permutator && \
  print "Error: permutator not found, and your compiler is broken!" && \
  return 1

alias permutator="./permutator"

! isfile ./input && \
  print "Error: cannot find puzzle input! are you in the right directory?" && \
  return 1

## fetch input
daysev_input_raw=$(fox-fr ./input)
#conv to array
unset daysev_input
declare -a daysev_input
IFS=$'\n'
for input_raw in $=daysev_input_raw; do
  daysev_input+=("$input_raw")
done
unset IFS

## operators for testing purpose
operators=('*'
           '+')


## iterate over each array indice
IFS=$'\n'
for indice in $=daysev_input; do
  #separate result from equation
  unset ind_result
  unset ind_equation
  IFS=$':'
  for sep in $=indice; do
   ! [ -z "$ind_result" ] && \
    ind_equation=$sep || \
    ind_result=$sep
  done
  unset IFS
  print "target result: "$ind_result""
  print "numbers to check: "$ind_equation""
  print ''
  print "begin check"
  print ''
  #fetch equation length
  equation_length=0
  IFS=$' '
  for eq_count in $=ind_equation; do
    equation_length=$((equation_length+1))
  done
  unset IFS
  #operator count
  operator_count=$((equation_length-1))
  #fetch possible permutations of operators for length
  ind_permut_raw=$(permutator $operator_count)
  #convert possible permutations to array
  unset ind_permut_arr
  declare -a ind_permut_arr
  IFS=$'\n'
    for permut_cln in $=ind_permut_raw; do
      ind_permut_arr+=("$permut_cln")
    done
  unset IFS
done
unset IFS

